package com.dan.navigationcompoentdemo

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.fragment.findNavController
import com.dan.navigationcompoentdemo.model.User
import kotlinx.android.synthetic.main.fragment_a.view.*

class FragmentA : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        val view = inflater.inflate(R.layout.fragment_a, container, false)

        //when send btn clicks
        view.btn_send.setOnClickListener {

            val firstName = view.et_edit_text1.text.toString()
            val lastName = view.et_edit_text2.text.toString()
            val user = User(firstName, lastName)
            //FragmentADirections.actionFragmentAToFragmentB is generated by compiler
            val action = FragmentADirections.actionFragmentAToFragmentB(currentUser = user)

            findNavController().navigate(action)
        }
        return view
    }

}